<a href="https://colab.research.google.com/github/yashveersinghsohi/Dive_into_Deep_Learning_Practice/blob/chapter_2.3/chapter_2/ch_2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Book Link](https://d2l.ai/chapter_preliminaries/linear-algebra.html)

# Imports

In [1]:
import torch

# Scalars

In [2]:
x, y = torch.tensor(3.0), torch.tensor(2.0)
x+y, x-y, x*y, x/y, x**y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

# Vectors

In [7]:
x = torch.arange(3)
x, x[2], len(x), x.shape, x.shape[0]

(tensor([0, 1, 2]), tensor(2), 3, torch.Size([3]), 3)

# Matrices

In [9]:
A = torch.arange(6).reshape(3, 2)
A, A.T

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 2, 4],
         [1, 3, 5]]))

In [12]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A, A.T, A==A.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

# Tensors

In [13]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

# Tensor Arithmetic

In [16]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
a = 2
A, A+B, A*B, A+a

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]),
 tensor([[2., 3., 4.],
         [5., 6., 7.]]))

# Reduction

In [17]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [23]:
(A, A.sum(), A.sum(axis=0), A.sum(axis=1), 
 A.sum(axis=0, keepdim=True), A.sum(axis=1, keepdim=True), 
 A/A.sum(axis=1, keepdim=True))

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(15.),
 tensor([3., 5., 7.]),
 tensor([ 3., 12.]),
 tensor([[3., 5., 7.]]),
 tensor([[ 3.],
         [12.]]),
 tensor([[0.0000, 0.3333, 0.6667],
         [0.2500, 0.3333, 0.4167]]))

In [21]:
A, A.mean(), A.mean(axis=0), A.mean(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(2.5000),
 tensor([1.5000, 2.5000, 3.5000]),
 tensor([1., 4.]))

In [27]:
A, A.cumsum(axis=0), A.cumsum(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 5., 7.]]),
 tensor([[ 0.,  1.,  3.],
         [ 3.,  7., 12.]]))

# Dot Products

In [30]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y), torch.sum(x*y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.), tensor(3.))

# Matrix Vector Products

In [31]:
A, A.shape, x, x.shape, torch.mv(A, x), A@x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor([0., 1., 2.]),
 torch.Size([3]),
 tensor([ 5., 14.]),
 tensor([ 5., 14.]))

# Matrix-Matrix Multiplication

In [33]:
B = torch.ones(3, 4)
A, B, torch.mm(A, B), A@B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

# Norm

In [36]:
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.norm(u, p=1), torch.abs(u).sum()

(tensor(5.), tensor(7.), tensor(7.))