<a href="https://colab.research.google.com/github/yashveersinghsohi/Dive_into_Deep_Learning_Practice/blob/chapter_2.5/chapter_2/ch_2_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Book Link](https://d2l.ai/chapter_preliminaries/calculus.html)

# Imports

In [1]:
import torch

# A Simple Function

In [6]:
x = torch.arange(4, dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

In [7]:
x.requires_grad_(True)
x.requires_grad, x.grad

(True, None)

In [8]:
y = 2*torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [9]:
y.backward()

In [10]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [11]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

# Backward for non-scalar variables

In [12]:
x.grad.zero_()
y = x*x
y.backward(gradient=torch.ones(len(y)))
x.grad

tensor([0., 2., 4., 6.])

# Detaching Computation

In [13]:
x.grad.zero_()
y = x*x
u = y.detach()
z = x*u
z.sum().backward()
x.grad, u

(tensor([0., 1., 4., 9.]), tensor([0., 1., 4., 9.]))

In [14]:
x.grad.zero_()
y.sum().backward()
x.grad, x

(tensor([0., 2., 4., 6.]), tensor([0., 1., 2., 3.], requires_grad=True))

# Gradients and Python Control Flow

In [17]:
def f(a):
  b = a * 2
  while b.norm() < 1000: b = b * 2
  if b.sum() > 0: c = b
  else: c = 100 * b
  return c

In [19]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a, d, a.grad

(tensor(-0.3027, requires_grad=True),
 tensor(-124000.5703, grad_fn=<MulBackward0>),
 tensor(409600.))