<a href="https://colab.research.google.com/github/yashveersinghsohi/Dive_into_Deep_Learning_Practice/blob/ch_2.1/chapter_2/ch_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Book Link](https://d2l.ai/chapter_preliminaries/ndarray.html)

# Imports

In [1]:
import torch

# Getting Started

In [4]:
torch.arange(12, dtype=torch.float32)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x = torch.arange(12, dtype=torch.float32)
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [9]:
x.reshape(3, 4)
x.reshape(3, -1)
x.reshape(-1, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
torch.zeros(size=(2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones(size=(2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
torch.randn(size=(2, 3, 4))

tensor([[[-0.9341,  1.6312, -0.5148,  0.6388],
         [-0.3448,  0.4127,  0.3752, -0.0331],
         [ 1.9368,  1.1841,  0.8582, -0.8862]],

        [[-0.9615,  0.0364,  1.9441,  0.3058],
         [ 1.5680, -1.7962,  0.2523,  0.5336],
         [ 0.4415, -0.8528,  0.4470,  0.9358]]])

In [15]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Indexing and Slicing

In [16]:
x[-1]

tensor([7, 8, 9])

In [17]:
x[1:3]

tensor([[4, 5, 6],
        [7, 8, 9]])

In [18]:
x[1, 2] = 17
x

tensor([[ 1,  2,  3],
        [ 4,  5, 17],
        [ 7,  8,  9]])

In [19]:
x[:2, :] = 100

In [20]:
x

tensor([[100, 100, 100],
        [100, 100, 100],
        [  7,   8,   9]])

# Operations

In [22]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02],
        [1.0966e+03, 2.9810e+03, 8.1031e+03]])

In [24]:
x = torch.tensor([1, 2, 3, 4, 5])
y = torch.tensor([5, 4, 3, 2, 1])
x+y, x-y, x*y, x/y, x**y

(tensor([6, 6, 6, 6, 6]),
 tensor([-4, -2,  0,  2,  4]),
 tensor([5, 8, 9, 8, 5]),
 tensor([0.2000, 0.5000, 1.0000, 2.0000, 5.0000]),
 tensor([ 1, 16, 27, 16,  5]))

In [26]:
x, y = torch.ones(size=(3, 1)), torch.zeros(size=(3, 1))
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[1.],
         [1.],
         [1.],
         [0.],
         [0.],
         [0.]]),
 tensor([[1., 0.],
         [1., 0.],
         [1., 0.]]))

In [27]:
x.sum()

tensor(3.)

In [29]:
x==y, (x==y).sum()

(tensor([[False],
         [False],
         [False]]),
 tensor(0))

# Broadcasting

In [30]:
a, b = torch.arange(3).reshape(3, 1), torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [31]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [32]:
b+a

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# Saving Memory

In [33]:
id(a)

140434501331248

In [34]:
a = a+b
id(a)

140434500096128

In [36]:
a, b

(tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 tensor([[0, 1]]))

In [37]:
z = torch.zeros_like(a)

In [38]:
z

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [39]:
print(id(z))
a, b = torch.arange(3).reshape(3, 1), torch.arange(2).reshape(1, 2)
z[:] = a+b
print(id(z))

140434501267232
140434501267232


# Conversion to other python objects

In [40]:
A = a.numpy()
type(A), type(a)

(numpy.ndarray, torch.Tensor)

In [42]:
a[0], a[0].item(), float(a[0]), int(a[0])

(tensor([0]), 0, 0.0, 0)